# This file specifies the application's runtime configuration
# including URL routing, versions, static file uploads, etc. See
# https://docs.cloud.google.com/appengine/docs/standard/reference/app-yaml?tab=go#top
# for details.

# For the standard environment, the runtime is required and must include the version 
# (in this case go 1.25). You do not have to specificy the env.
runtime: go125

# For the flexible environment, the runtime is set to 'go' and you specify a runtime_config.
# the runtime_version is optional, but if you want to use a specific version of Go, you must specify it here.
# See https://cloud.google.com/appengine/docs/flexible/go/runtime for details.
# runtime: go
# env: flex
# runtime_config:
#   operating_system: 'ubuntu22'
#   runtime_version: 1.25



